[package]
name = "csv-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
log = "0.4.26"
env_logger = "0.11.7"
clap = { version = "4", features = ["derive"] }
ratatui = "0.29.0"
crossterm = "0.28.1"
color-eyre = "0.6.3"
